fix(deps): upgrade dependencies to fix vulnerable issues
mattrglobal/node-bbs-signatures pull request #196
Opened 2022-06-20 02:49 UTC by ivan-mattr

## Description

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [ ] Changes follow the **[contributing](../CONTRIBUTING.md)** document.

## Motivation and Context

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Which merge strategy will you use?

- [ ] Squash
- [ ] Rebase (REVIEW COMMITS)

2022-06-20 03:15 UTC, ZedMattr commented on package.json
>      "@commitlint/cli": "11.0.0",
These two might better also be updated the same way as:
https://github.com/mattrglobal/bbs-signatures/pull/131/files

Also husky might also need to be updated to 8.0

2022-06-20 22:51 UTC, ivan-mattr commented on .github/workflows/push-binary-dispatch.yml
>              node-version: 16.x
Hi @tplooker 
Per the conversations in slack, only node 14 and 16 are in scope,  but the jest test has problems to run with node 14 and 16 on Windows, so basically this job `build_win_pub_binaries` is gonna be ignored at all, I guess there is no binary for Windows be published.

2022-06-20 22:57 UTC, ivan-mattr commented on .github/workflows/push-binary-dispatch.yml
> +      - run: yarn test # Or shall the test step be skipped?
@tplooker 
If this `build_win_pub_binaries` job is required, maybe have to skip the test step?

2022-06-21 21:19 UTC, ivan-mattr commented on .github/workflows/push-binary-dispatch.yml
>              node-version: 16.x
Per conversation with @tplooker , removed this redundant Windows build job.

2022-06-21 22:57 UTC, tplooker commented on .github/workflows/push-binary-dispatch.yml
>  jobs:
Can you remove the windows option from the workflow_dispatch option above?

2022-06-21 23:54 UTC, ZedMattr approved these changes

2022-06-21 23:55 UTC, ZedMattr commented
Lets add a breaking change commit to signal this will be breaking changes.

2022-06-21 23:57 UTC, ZedMattr requested changes
Lets add a breaking change commit to auto upgrade versions.

2022-06-22 00:55 UTC, ZedMattr approved these changes

2022-06-22 01:38 UTC, merged